# Generated by Django 2.2.12 on 2020-06-08 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CalculatorSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("iva", models.FloatField()),
                ("tax", models.FloatField()),
                ("equip_rent_t20", models.FloatField()),
                ("equip_rent_t20dha", models.FloatField()),
                ("equip_rent_t21", models.FloatField()),
                ("equip_rent_t21dha", models.FloatField()),
                ("equip_rent_t30", models.FloatField()),
                ("equip_rent_t31", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("logo", models.ImageField(blank=True, null=True, upload_to="")),
                ("priority", models.IntegerField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("picture", models.ImageField(upload_to="")),
                ("description", models.TextField()),
                (
                    "tarif",
                    models.CharField(
                        choices=[
                            ("2.0A", "2.0A"),
                            ("2.0DHA", "2.0DHA"),
                            ("2.0DHS", "2.0DHS"),
                            ("2.1A", "2.1A"),
                            ("2.1DHA", "2.1DHA"),
                            ("2.1DHS", "2.1DHS"),
                            ("3.0A", "3.0A"),
                            ("3.1A", "3.1A"),
                        ],
                        max_length=10,
                    ),
                ),
                ("power_min", models.FloatField(blank=True, null=True)),
                ("power_max", models.FloatField(blank=True, null=True)),
                ("consumption_min", models.FloatField(blank=True, null=True)),
                ("consumption_max", models.FloatField(blank=True, null=True)),
                (
                    "client_type",
                    models.IntegerField(choices=[(0, "Individual"), (1, "Business")]),
                ),
                ("p1", models.FloatField()),
                ("p2", models.FloatField()),
                ("p3", models.FloatField()),
                ("c1", models.FloatField()),
                ("c2", models.FloatField()),
                ("c3", models.FloatField()),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="calculator.Company",
                    ),
                ),
            ],
        ),
    ]
