# Generated by Django 3.1 on 2020-09-07 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='agent_comission',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='offer',
            name='canal_comission',
            field=models.IntegerField(default=0),
        ),
    ]
