# Generated by Django 3.1 on 2020-09-11 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_auto_20200907_1237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='agent_comission',
            new_name='agent_commission',
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='canal_comission',
            new_name='canal_commission',
        ),
    ]
