# Generated by Django 3.0.7 on 2020-06-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_auto_20200610_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='uuid',
            field=models.UUIDField(unique=True),
        ),
    ]
