# Generated by Django 3.0.7 on 2020-06-10 14:15

import apps.calculator.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_auto_20200610_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=apps.calculator.fields.NameField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='name',
            field=apps.calculator.fields.NameField(max_length=255),
        ),
    ]
