# Generated by Django 3.1 on 2020-09-21 14:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0004_auto_20200911_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='required_fields',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('photo_cif1', 'Photo CIF'), ('photo_dni1', 'Photo DNI'), ('photo_dni2', 'Photo DNI reverse side'), ('photo_factura', 'Photo factura'), ('photo_factura_1', 'Photo factura reverse side'), ('photo_recibo1', 'Photo Recibo de Autónomo'), ('recibo1', 'Recibo de Autónomo'), ('cif', 'CIF'), ('dni', 'DNI'), ('phone', 'Phone')], max_length=30), blank=True, null=True, size=None),
        ),
    ]
