# Generated by Django 3.0.7 on 2020-06-18 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0005_remove_offer_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="calculatorsettings", name="equip_rent_t20dhs", field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name="calculatorsettings", name="equip_rent_t21dhs", field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name="calculatorsettings", name="equip_rent_t20", field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name="calculatorsettings", name="equip_rent_t20dha", field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name="calculatorsettings", name="equip_rent_t21", field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name="calculatorsettings", name="equip_rent_t21dha", field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name="calculatorsettings", name="equip_rent_t30", field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name="calculatorsettings", name="equip_rent_t31", field=models.FloatField(default=1),
        ),
        migrations.AlterField(model_name="calculatorsettings", name="iva", field=models.FloatField(default=1),),
        migrations.AlterField(model_name="calculatorsettings", name="tax", field=models.FloatField(default=1),),
    ]
