# Generated by Django 3.1 on 2020-09-21 20:48

import apps.calculator.fields
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0005_offer_required_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='name',
            field=apps.calculator.fields.NameField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='offer',
            name='required_fields',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('photo_cif', 'Photo CIF'), ('photo_dni', 'Photo DNI'), ('photo_dni_repr_legal', 'Photo DNI representante legal'), ('photo_factura', 'Photo factura'), ('photo_recibo', 'Photo Recibo de Autónomo'), ('cif', 'CIF'), ('dni', 'DNI'), ('dni_repr', 'DNI representante legal'), ('phone', 'Phone'), ('name_changed_doc', 'DOCUMENTO CAMBIO DE NOMBRE'), ('contrato_arredamiento', 'CONTRATO ARREDAMIENTO/COMPRAVENTA')], max_length=30), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='offer',
            name='tarif',
            field=models.CharField(choices=[('2.0A', '2.0A'), ('2.0DHA', '2.0DHA'), ('2.0DHS', '2.0DHS'), ('2.1A', '2.1A'), ('2.1DHA', '2.1DHA'), ('2.1DHS', '2.1DHS'), ('3.0A', '3.0A'), ('3.1A', '3.1A')], db_index=True, max_length=10),
        ),
    ]
