# Generated by Django 3.0.7 on 2020-06-18 03:54

from django.db import migrations
import utils


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0006_auto_20200618_0306"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offer", name="c1", field=utils.PositiveNullableFloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="offer", name="c2", field=utils.PositiveNullableFloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="offer", name="c3", field=utils.PositiveNullableFloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="offer", name="p1", field=utils.PositiveNullableFloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="offer", name="p2", field=utils.PositiveNullableFloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="offer", name="p3", field=utils.PositiveNullableFloatField(blank=True, null=True),
        ),
    ]
