# Generated by Django 3.0.7 on 2020-07-22 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0008_auto_20200629_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='is_price_permanent',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
