# Generated by Django 3.0.7 on 2020-07-30 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0009_offer_is_price_permanent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offer",
            name="is_price_permanent",
            field=models.CharField(choices=[("Fijo", "Fijo"), ("Indexado", "Indexado")], max_length=20),
        ),
    ]
