# Generated by Django 3.1.2 on 2020-10-07 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0009_auto_20201002_1320"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="offer",
            name="uuid",
        ),
    ]
