# Generated by Django 3.1.2 on 2020-11-03 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0010_remove_offer_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='offer_status_used',
            field=models.BooleanField(default=False),
        ),
    ]
