# Generated by Django 3.1.2 on 2020-11-04 11:04

import apps.calculator.fields
from django.db import migrations, models

import apps.calculator.validators


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0011_company_offer_status_used"),
    ]

    operations = [
        migrations.AddField(
            model_name="calculatorsettings",
            name="equip_rent_g31",
            field=models.FloatField(default=0.6, validators=[apps.calculator.validators.is_positive]),
        ),
        migrations.AddField(
            model_name="calculatorsettings",
            name="equip_rent_g32",
            field=models.FloatField(default=1.1, validators=[apps.calculator.validators.is_positive]),
        ),
        migrations.AddField(
            model_name="calculatorsettings",
            name="equip_rent_g33",
            field=models.FloatField(default=12.5, validators=[apps.calculator.validators.is_positive]),
        ),
        migrations.AddField(
            model_name="calculatorsettings",
            name="equip_rent_g34",
            field=models.FloatField(default=12.5, validators=[apps.calculator.validators.is_positive]),
        ),
    ]
