# Generated by Django 3.1.2 on 2020-11-04 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0012_auto_20201104_1104"),
    ]

    operations = [
        migrations.AddField(
            model_name="calculatorsettings",
            name="igic",
            field=models.FloatField(default=0.04),
        ),
    ]
