# Generated by Django 3.1.2 on 2020-11-04 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0013_calculatorsettings_igic"),
    ]

    operations = [
        migrations.AddField(
            model_name="calculatorsettings",
            name="carbon_tax",
            field=models.FloatField(default=0.00234),
        ),
        migrations.AlterField(
            model_name="calculatorsettings",
            name="igic",
            field=models.FloatField(default=0.03),
        ),
    ]
