# Generated by Django 3.1.2 on 2020-11-13 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0014_auto_20201104_1206"),
    ]

    operations = [
        migrations.AddField(
            model_name="offer",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
