# Generated by Django 3.1.5 on 2021-06-16 15:50

from django.db import migrations, models
from apps.calculator.models import Tarif


def migrate_tarifs(apps, _):
    offer_model = apps.get_model('calculator', 'Offer')
    offers = offer_model.objects.filter(tarif__startswith='2')
    offers.update(tarif=Tarif.T20TD.value)



class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0018_auto_20210601_1404'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calculatorsettings',
            old_name='equip_rent_t20',
            new_name='equip_rent_t20td',
        ),
        migrations.RemoveField(
            model_name='calculatorsettings',
            name='equip_rent_t20dha',
        ),
        migrations.RemoveField(
            model_name='calculatorsettings',
            name='equip_rent_t20dhs',
        ),
        migrations.RemoveField(
            model_name='calculatorsettings',
            name='equip_rent_t21',
        ),
        migrations.RemoveField(
            model_name='calculatorsettings',
            name='equip_rent_t21dha',
        ),
        migrations.RemoveField(
            model_name='calculatorsettings',
            name='equip_rent_t21dhs',
        ),
        migrations.AlterField(
            model_name='offer',
            name='tarif',
            field=models.CharField(choices=[('3.0A', '3.0A'), ('3.1A', '3.1A'), ('3.1', '3.1'), ('3.2', '3.2'), ('3.3', '3.3'), ('3.4', '3.4'), ('2.0TD', '2.0TD'), ('3.0TD', '3.0TD'), ('6.1TD', '6.1TD')], db_index=True, max_length=10),
        ),
        migrations.RunPython(migrate_tarifs, reverse_code=migrations.RunPython.noop),
    ]
