# Generated by Django 3.1.5 on 2021-06-16 15:59

from django.db import migrations, models
from apps.calculator.models import Tarif

def migrate_tarifs(apps, _):
    offer_model = apps.get_model('calculator', 'Offer')
    offers = offer_model.objects.filter(tarif='3.1A')
    offers.update(tarif=Tarif.T61TD.value)


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0020_auto_20210616_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='tarif',
            field=models.CharField(choices=[('3.1', '3.1'), ('3.2', '3.2'), ('3.3', '3.3'), ('3.4', '3.4'), ('2.0TD', '2.0TD'), ('3.0TD', '3.0TD'), ('6.1TD', '6.1TD')], db_index=True, max_length=10),
        ),
        migrations.RunPython(migrate_tarifs, reverse_code=migrations.RunPython.noop),
    ]
