# Generated by Django 3.1.5 on 2021-06-16 16:13

import clients.utils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0021_auto_20210616_1559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calculatorsettings',
            old_name='equip_rent_t30',
            new_name='equip_rent_t30td',
        ),
        migrations.RenameField(
            model_name='calculatorsettings',
            old_name='equip_rent_t31',
            new_name='equip_rent_t61td',
        ),
        migrations.AddField(
            model_name='offer',
            name='c4',
            field=clients.utils.PositiveNullableFloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='c5',
            field=clients.utils.PositiveNullableFloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='c6',
            field=clients.utils.PositiveNullableFloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='p4',
            field=clients.utils.PositiveNullableFloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='p5',
            field=clients.utils.PositiveNullableFloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='p6',
            field=clients.utils.PositiveNullableFloatField(blank=True, null=True),
        ),
    ]
