# Generated by Django 3.1.5 on 2021-07-14 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0023_auto_20210628_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriorityOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('luz', 'Luz'), ('gas', 'gas')], default='luz', max_length=3)),
                ('tarif', models.CharField(choices=[('3.1', '3.1'), ('3.2', '3.2'), ('3.3', '3.3'), ('3.4', '3.4'), ('2.0TD', '2.0TD'), ('3.0TD', '3.0TD'), ('6.1TD', '6.1TD')], max_length=10)),
                ('power_min', models.FloatField()),
                ('power_max', models.FloatField()),
                ('consumption_min', models.FloatField()),
                ('consumption_max', models.FloatField()),
                ('first', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_offer', to='calculator.offer')),
                ('second', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_offer', to='calculator.offer')),
                ('third', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='third_offer', to='calculator.offer')),
            ],
        ),
    ]
