# Generated by Django 3.1.5 on 2021-07-14 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0024_priorityoffer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculatorsettings',
            name='equip_rent_t61td',
        ),
        migrations.AlterField(
            model_name='offer',
            name='tarif',
            field=models.CharField(choices=[('3.1', '3.1'), ('3.2', '3.2'), ('3.3', '3.3'), ('3.4', '3.4'), ('2.0TD', '2.0TD'), ('3.0TD', '3.0TD')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='priorityoffer',
            name='tarif',
            field=models.CharField(choices=[('3.1', '3.1'), ('3.2', '3.2'), ('3.3', '3.3'), ('3.4', '3.4'), ('2.0TD', '2.0TD'), ('3.0TD', '3.0TD')], max_length=10),
        ),
    ]
