# Generated by Django 3.1.5 on 2021-07-16 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0025_auto_20210714_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='calculator',
            field=models.BooleanField(default=True),
        ),
    ]
