# Generated by Django 3.1.5 on 2021-07-16 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0026_offer_calculator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculatorsettings',
            name='equip_rent_g31',
        ),
        migrations.RemoveField(
            model_name='calculatorsettings',
            name='equip_rent_g32',
        ),
        migrations.RemoveField(
            model_name='calculatorsettings',
            name='equip_rent_g33',
        ),
        migrations.RemoveField(
            model_name='calculatorsettings',
            name='equip_rent_g34',
        ),
        migrations.RemoveField(
            model_name='calculatorsettings',
            name='equip_rent_t20td',
        ),
        migrations.RemoveField(
            model_name='calculatorsettings',
            name='equip_rent_t30td',
        ),
        migrations.RemoveField(
            model_name='calculatorsettings',
            name='igic',
        ),
        migrations.RemoveField(
            model_name='calculatorsettings',
            name='iva',
        ),
    ]
