# Generated by Django 3.1.5 on 2021-12-10 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0028_auto_20210728_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='tarif',
            field=models.CharField(choices=[('3.1', '3.1'), ('3.2', '3.2'), ('3.3', '3.3'), ('3.4', '3.4'), ('2.0TD', '2.0TD'), ('3.0TD', '3.0TD'), ('6.1TD', '6.1TD')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='priorityoffer',
            name='tarif',
            field=models.CharField(choices=[('3.1', '3.1'), ('3.2', '3.2'), ('3.3', '3.3'), ('3.4', '3.4'), ('2.0TD', '2.0TD'), ('3.0TD', '3.0TD'), ('6.1TD', '6.1TD')], max_length=10),
        ),
    ]
