KO = "KO"
KO_PAPELLERA = "KO (papellera)"
PENDIENTE_TRAMITACION = "Pendiente tramitación"
TRAMITACION = "Tramitación en proceso"
PENDIENTE_PAGO = "Pendiente Pago"
PAGADO = "Pagado"

TRAMITACION_STATUSES = KO, PENDIENTE_TRAMITACION, TRAMITACION
FACTURACION_STATUSES = PENDIENTE_PAGO, PAGADO
CLIENT_STATUSES = PENDIENTE_PAGO, PAGADO

ALL_STATUSES = (
    KO,
    KO_PAPELLERA,
    PENDIENTE_TRAMITACION,
    TRAMITACION,
    PENDIENTE_PAGO,
    PAGADO,
)
