# Generated by Django 3.0.7 on 2020-08-08 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bids', '0002_auto_20200808_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tramitacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc', models.BooleanField(null=True)),
                ('call', models.BooleanField(null=True)),
                ('scoring', models.BooleanField(null=True)),
                ('bid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bids.Bid')),
            ],
            options={
                'db_table': 'tramitacion',
            },
        ),
    ]
