# Generated by Django 3.0.7 on 2020-08-08 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0004_auto_20200808_1906'),
        ('tramitacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramitacion',
            name='bid',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='bids.Bid'),
        ),
        migrations.AlterField(
            model_name='tramitacion',
            name='call',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tramitacion',
            name='doc',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tramitacion',
            name='scoring',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
