# Generated by Django 3.0.7 on 2020-08-08 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0004_auto_20200808_1906'),
        ('tramitacion', '0002_auto_20200808_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramitacion',
            name='bid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bids.Bid'),
        ),
    ]
