# Generated by Django 3.0.7 on 2020-08-09 02:11

import django.contrib.postgres.fields
from django.db import migrations, models

import apps.users.models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="permissions",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("profile", "Profile"),
                        ("bids", "Bids"),
                        ("offers", "Offers"),
                        ("calculator", "Calculator"),
                    ],
                    max_length=30,
                ),
                default=apps.users.models.get_default_user_permissions,
                help_text="Valores posibles: profile, bids, offers, calculator",
                size=None,
            ),
        ),
    ]
