# Generated by Django 3.0.7 on 2020-06-12 11:45

import apps.users.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="phone",
            field=apps.users.models.PhoneNumberField(blank=True, max_length=9, null=True, verbose_name="phone number"),
        ),
    ]
