# Generated by Django 3.0.7 on 2020-06-12 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customuser_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser", name="can_see_calculator_and_offers", field=models.BooleanField(default=True),
        ),
    ]
