# Generated by Django 3.1 on 2020-08-14 15:11

import apps.users.models
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200809_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='permissions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('profile', 'Profile'), ('bids', 'Bids'), ('offers', 'Offers'), ('calculator', 'Calculator')], max_length=30), default=apps.users.models.get_default_user_permissions, help_text='Possible values: profile, bids, offers, calculator', size=None),
        ),
        migrations.AlterField(
            model_name='punto',
            name='address',
            field=apps.users.models.MyCharField(blank=True, max_length=255, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='punto',
            name='locality',
            field=apps.users.models.MyCharField(blank=True, max_length=255, null=True, verbose_name='Locality'),
        ),
        migrations.AlterField(
            model_name='punto',
            name='postalcode',
            field=apps.users.models.MyCharField(blank=True, max_length=5, null=True, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Postalcode'),
        ),
        migrations.AlterField(
            model_name='punto',
            name='province',
            field=apps.users.models.MyCharField(blank=True, choices=[('A Coruña', 'A Coruña'), ('Álava', 'Álava'), ('Albacete', 'Albacete'), ('Alicante', 'Alicante'), ('Almería', 'Almería'), ('Asturias', 'Asturias'), ('Ávila', 'Ávila'), ('Badajoz', 'Badajoz'), ('Baleares', 'Baleares'), ('Barcelona', 'Barcelona'), ('Burgos', 'Burgos'), ('Cáceres', 'Cáceres'), ('Cádiz', 'Cádiz'), ('Cantabria', 'Cantabria'), ('Castellón', 'Castellón'), ('Ciudad Real', 'Ciudad Real'), ('Córdoba', 'Córdoba'), ('Cuenca', 'Cuenca'), ('Girona', 'Girona'), ('Granada', 'Granada'), ('Guadalajara', 'Guadalajara'), ('Gipuzkoa', 'Gipuzkoa'), ('Huelva', 'Huelva'), ('Huesca', 'Huesca'), ('Jaén', 'Jaén'), ('La Rioja', 'La Rioja'), ('Las Palmas', 'Las Palmas'), ('León', 'León'), ('Lérida', 'Lérida'), ('Lugo', 'Lugo'), ('Madrid', 'Madrid'), ('Málaga', 'Málaga'), ('Murcia', 'Murcia'), ('Navarra', 'Navarra'), ('Ourense', 'Ourense'), ('Palencia', 'Palencia'), ('Pontevedra', 'Pontevedra'), ('Salamanca', 'Salamanca'), ('Segovia', 'Segovia'), ('Sevilla', 'Sevilla'), ('Soria', 'Soria'), ('Tarragona', 'Tarragona'), ('Santa Cruz de Tenerife', 'Santa Cruz de Tenerife'), ('Teruel', 'Teruel'), ('Toledo', 'Toledo'), ('Valencia', 'Valencia'), ('Valladolid', 'Valladolid'), ('Vizcaya', 'Vizcaya'), ('Zamora', 'Zamora'), ('Zaragoza', 'Zaragoza')], max_length=255, null=True, verbose_name='Province'),
        ),
    ]
