# Generated by Django 3.0.7 on 2020-06-16 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_usersettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                blank=True, choices=[(None, "Client"), ("support", "Support")], max_length=10, null=True
            ),
        ),
    ]
