# Generated by Django 3.1 on 2020-08-24 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0006_auto_20200818_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='under_responsibility', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='invites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[(None, 'Client'), ('support', 'Support'), ('admin', 'Admin'),
                                                        ('agent', 'Agent'), ('affiliate', 'Affiliate')], max_length=10,
                                   null=True),
        ),
    ]
