# Generated by Django 3.1 on 2020-08-24 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200824_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='punto',
            name='dni',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='punto',
            name='legal_representative',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
