# Generated by Django 3.0.7 on 2020-06-22 12:45

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_auto_20200616_1546"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="Email address"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="phone",
            field=apps.users.models.PhoneNumberField(blank=True, max_length=9, null=True, verbose_name="Phone number"),
        ),
    ]
