# Generated by Django 3.1 on 2020-08-28 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_delete_call"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BackendPhone",
        ),
    ]
