# Generated by Django 3.0.7 on 2020-07-10 23:14

import apps.users.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0008_auto_20200629_2055'),
        ('users', '0012_customuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cif_dni',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CIF/DNI'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='company_changed',
            field=models.BooleanField(default=False, verbose_name='Is company changed?'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='company_changed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Company changed at'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='dni',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='DNI'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='iban',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='IBAN'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='legal_representative',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Legal representative'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='source',
            field=models.CharField(choices=[('default', 'Default')], default='default', max_length=30),
        ),
        migrations.CreateModel(
            name='Punto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', apps.users.models.MyCharField(blank=True, max_length=100, null=True)),
                ('province', apps.users.models.MyCharField(blank=True, max_length=100, null=True)),
                ('poblacion', apps.users.models.MyCharField(blank=True, max_length=100, null=True)),
                ('direccion', apps.users.models.MyCharField(blank=True, max_length=100, null=True)),
                ('postalcode', apps.users.models.MyCharField(blank=True, max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(5)])),
                ('last_time_company_luz_changed', models.DateField(blank=True, null=True)),
                ('last_time_company_gas_changed', models.DateField(blank=True, null=True)),
                ('cups_luz', apps.users.models.MyCharField(blank=True, max_length=100, null=True)),
                ('cups_gas', apps.users.models.MyCharField(blank=True, max_length=100, null=True)),
                ('tarif_luz', apps.users.models.MyCharField(blank=True, max_length=100, null=True)),
                ('tarif_gas', apps.users.models.MyCharField(blank=True, max_length=100, null=True)),
                ('p1', models.FloatField(blank=True, null=True)),
                ('p2', models.FloatField(blank=True, null=True)),
                ('p3', models.FloatField(blank=True, null=True)),
                ('c1', models.FloatField(blank=True, null=True)),
                ('c2', models.FloatField(blank=True, null=True)),
                ('c3', models.FloatField(blank=True, null=True)),
                ('consumo_annual_luz', models.FloatField(blank=True, null=True)),
                ('consumo_annual_gas', models.FloatField(blank=True, null=True)),
                ('company_gas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_gas', to='calculator.Company')),
                ('company_luz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_luz', to='calculator.Company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'puntos',
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_type', models.CharField(choices=[('mobile', 'Mobile'), ('city', 'City')], max_length=6)),
                ('number', models.CharField(max_length=9, validators=[apps.users.models.phone_number_validator])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'phones',
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_type', models.CharField(choices=[('factura', 'Factura'), ('factura_1', 'Factura reverso'), ('dni1', 'DNI'), ('dni2', 'DNI reverse side'), ('cif1', 'CIF'), ('cif2', 'CIF reverse side')], max_length=10)),
                ('attachment', models.FileField(upload_to='')),
                ('punto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='users.Punto')),
            ],
        ),
    ]
