# Generated by Django 3.0.7 on 2020-07-10 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0016_auto_20200710_2258'),
        ('users', '0013_auto_20200710_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='punto',
            name='bid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bids.Bid'),
            preserve_default=False,
        ),
    ]
