# Generated by Django 3.1 on 2020-09-15 13:10

import apps.users.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_customuser_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='agent_type',
            field=models.CharField(blank=True, choices=[('agent', 'Agent'), ('canal', 'Canal'), ('fixed', 'Agent with fixed salary')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='permissions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('profile', 'Profile'), ('bids', 'Bids'), ('offers', 'Offers'), ('calculator', 'Calculator'), ('leeds_access', 'Leeds')], max_length=30), default=apps.users.models.get_default_user_permissions, help_text='Possible values: profile, bids, offers, calculator, leeds_access', size=None),
        ),
    ]
