# Generated by Django 3.0.7 on 2020-07-11 15:52

import apps.users.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_punto_bid"),
    ]

    operations = [
        migrations.RemoveField(model_name="punto", name="direccion",),
        migrations.RemoveField(model_name="punto", name="poblacion",),
        migrations.AddField(
            model_name="punto",
            name="address",
            field=apps.users.models.MyCharField(blank=True, max_length=100, null=True, verbose_name="Address"),
        ),
        migrations.AddField(
            model_name="punto",
            name="locality",
            field=apps.users.models.MyCharField(blank=True, max_length=100, null=True, verbose_name="Locality"),
        ),
        migrations.AlterField(
            model_name="punto",
            name="consumo_annual_gas",
            field=models.FloatField(blank=True, null=True, verbose_name="Annual consumption (gas)"),
        ),
        migrations.AlterField(
            model_name="punto",
            name="consumo_annual_luz",
            field=models.FloatField(blank=True, null=True, verbose_name="Annual consumption"),
        ),
        migrations.AlterField(
            model_name="punto",
            name="cups_gas",
            field=apps.users.models.MyCharField(blank=True, max_length=100, null=True, verbose_name="CUPS gas"),
        ),
        migrations.AlterField(
            model_name="punto",
            name="cups_luz",
            field=apps.users.models.MyCharField(blank=True, max_length=100, null=True, verbose_name="CUPS"),
        ),
        migrations.AlterField(
            model_name="punto",
            name="name",
            field=apps.users.models.MyCharField(blank=True, max_length=100, null=True, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="punto", name="p1", field=models.FloatField(blank=True, help_text="Power 1", null=True),
        ),
        migrations.AlterField(
            model_name="punto",
            name="postalcode",
            field=apps.users.models.MyCharField(
                blank=True,
                max_length=100,
                null=True,
                validators=[django.core.validators.MinLengthValidator(5)],
                verbose_name="Postalcode",
            ),
        ),
        migrations.AlterField(
            model_name="punto",
            name="province",
            field=apps.users.models.MyCharField(blank=True, max_length=100, null=True, verbose_name="Province"),
        ),
        migrations.AlterField(
            model_name="punto",
            name="tarif_gas",
            field=apps.users.models.MyCharField(blank=True, max_length=100, null=True, verbose_name="Tarif gas"),
        ),
        migrations.AlterField(
            model_name="punto",
            name="tarif_luz",
            field=apps.users.models.MyCharField(blank=True, max_length=100, null=True, verbose_name="Tarif"),
        ),
        migrations.AlterUniqueTogether(name="phone", unique_together={("phone_type", "user")},),
        migrations.RunSQL("DROP TABLE cards CASCADE;"),
    ]
