# Generated by Django 3.1 on 2020-09-16 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20200915_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='source',
            field=models.CharField(choices=[('default', 'Default'), ('call_n_visit', 'Call&Visit')], default='default', max_length=30),
        ),
    ]
