# Generated by Django 3.0.7 on 2020-07-17 17:32

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20200712_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackendPhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=9)),
            ],
            options={
                'db_table': 'backend_phone',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=apps.users.models.FreeswitchStorage(location='/freeswitch_recordings'), upload_to='')),
                ('called_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'calls_call',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=apps.users.models.PhoneNumberField(blank=True, max_length=9, null=True, validators=[apps.users.models.phone_number_validator], verbose_name='Phone number'),
        ),
    ]
