# Generated by Django 3.1 on 2020-09-16 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20200916_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='source',
            field=models.CharField(choices=[('default', 'Online'), ('call_n_visit', 'Call&Visit')], default='default', max_length=30),
        ),
    ]
