# Generated by Django 3.0.7 on 2020-07-17 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0008_auto_20200629_2055'),
        ('users', '0017_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='punto',
            name='company_gas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_gas', to='calculator.Company', verbose_name='Company gas'),
        ),
        migrations.AlterField(
            model_name='punto',
            name='company_luz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_luz', to='calculator.Company', verbose_name='Company light'),
        ),
    ]
