# Generated by Django 3.1 on 2020-09-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20200916_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='fecha_firma',
            field=models.DateField(blank=True, null=True),
        ),
    ]
