# Generated by Django 3.0.7 on 2020-07-21 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20200717_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='punto',
            name='last_time_company_gas_changed',
            field=models.DateField(blank=True, null=True, verbose_name='Last time company gas changed'),
        ),
        migrations.AlterField(
            model_name='punto',
            name='last_time_company_luz_changed',
            field=models.DateField(blank=True, null=True, verbose_name='Last time company light changed'),
        ),
    ]
