# Generated by Django 3.0.7 on 2020-07-22 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0020_auto_20200722_1328"),
    ]

    operations = [
        migrations.AddField(
            model_name="punto",
            name="category",
            field=models.CharField(
                choices=[("phisical", "Physical"), ("autonomous", "Autonomous"), ("business", "Business")],
                max_length=20,
                null=True,
            ),
        ),
    ]
