# Generated by Django 3.1 on 2020-09-21 19:18

import apps.users.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20200918_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='permissions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('profile', 'Profile'), ('bids', 'Bids'), ('offers', 'Offers'), ('calculator', 'Calculator'), ('leeds_access', 'Leeds')], max_length=30), default=apps.users.models.get_default_user_permissions, help_text='Possible values: p, r, o, f, i, l, e, ,, b, i, d, s, ,, o, f, f, e, r, s, ,, c, a, l, c, u, l, a, t, o, r', size=None),
        ),
    ]
