# Generated by Django 3.0.7 on 2020-07-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_punto_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='punto',
            name='category',
            field=models.CharField(choices=[('physical', 'Physical'), ('autonomous', 'Autonomous'), ('business', 'Business')], max_length=20, null=True),
        ),
    ]
