# Generated by Django 3.1 on 2020-09-22 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20200921_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='punto',
            name='cif',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='punto',
            name='repr_legal',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='attachment_type',
            field=models.CharField(choices=[('factura', 'Factura'), ('factura_1', 'Factura reverso'), ('dni1', 'DNI'), ('dni2', 'DNI reverse side'), ('cif1', 'CIF'), ('cif2', 'CIF reverse side'), ('recibo1', 'Recibo de Autónomo'), ('repr_legal', 'Foto DNI Representante Legal'), ('name_changed', 'Cambio de nombre'), ('arredamiento', 'Contrato arredamiento')], max_length=20),
        ),
    ]
