# Generated by Django 3.0.7 on 2020-07-22 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20200722_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='punto',
            name='category',
            field=models.CharField(choices=[('physical', 'Physical'), ('autonomous', 'Autonomous'), ('business', 'Business')], default='autonomous', max_length=20),
            preserve_default=False,
        ),
    ]
