# Generated by Django 3.0.7 on 2020-07-29 17:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20200722_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='punto',
            name='address',
            field=models.CharField(default='direccion', max_length=255, verbose_name='Address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='punto',
            name='iban',
            field=models.CharField(default='iban', max_length=255, verbose_name='IBAN'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='punto',
            name='locality',
            field=models.CharField(default='localidad', max_length=255, verbose_name='Locality'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='punto',
            name='postalcode',
            field=models.CharField(default='12345', max_length=5, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Postalcode'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='punto',
            name='province',
            field=models.CharField(choices=[('Madrid', 'Madrid'), ('Barcelona', 'Barcelona')], default='Madrid', max_length=255, verbose_name='Province'),
            preserve_default=False,
        ),
    ]
