# Generated by Django 3.1 on 2020-09-24 11:41

from django.db import migrations, models


def migrate_agent_type(apps, _):
    user_model = apps.get_model("users", "CustomUser")
    for user in user_model.objects.all():
        if user.agent_type == "fixed":
            user.agent_type = "agent"
            user.fixed = True
            user.save(update_fields=["fixed", "agent_type"])


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0024_remove_punto_repr_legal"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="fixed_salary",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.RunPython(migrate_agent_type, reverse_code=migrations.RunPython.noop),
    ]
