# Generated by Django 3.1 on 2020-09-24 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_customuser_fixed_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='canal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='agent_type',
            field=models.CharField(blank=True, choices=[('agent', 'Agent'), ('canal', 'Canal')], max_length=20, null=True),
        ),
    ]
