# Generated by Django 3.1 on 2020-09-24 13:14

import apps.users.models
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


def reset_permissions(apps, _):
    user_model = apps.get_model("users.CustomUser")
    user_model.objects.update(permissions=[])


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0026_auto_20200924_1245"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="canal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="agents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="permissions",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[("offers", "Offers"), ("calculator", "Calculator"), ("leeds_access", "Leeds")],
                    max_length=30,
                ),
                default=apps.users.models.get_default_user_permissions,
                help_text="Possible values: ",
                size=None,
            ),
        ),
        migrations.RunPython(reset_permissions, reverse_code=migrations.RunPython.noop),
    ]
