# Generated by Django 3.1.1 on 2020-09-28 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0027_auto_20200924_1314"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attachment",
            name="attachment_type",
            field=models.CharField(
                choices=[
                    ("factura", "Factura"),
                    ("factura_1", "Factura reverso"),
                    ("dni1", "DNI"),
                    ("dni2", "DNI reverse side"),
                    ("cif1", "CIF"),
                    ("cif2", "CIF reverse side"),
                    ("recibo1", "Recibo de Autónomo"),
                    ("repr_legal", "Foto DNI Representante Legal"),
                    ("name_changed", "Cambio de nombre"),
                    ("arredamiento", "Contrato arredamiento"),
                    ("factura_gas_1", "Factura GAS"),
                    ("factura_gas_2", "Factura GAS reverso"),
                ],
                max_length=20,
            ),
        ),
    ]
