# Generated by Django 3.1.1 on 2020-09-30 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0028_auto_20200928_1711"),
    ]

    operations = [
        migrations.AddField(
            model_name="punto",
            name="is_name_changed",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
