# Generated by Django 3.1 on 2020-09-30 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bids", "0016_bid_canal_paid"),
        ("users", "0029_punto_is_name_changed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="punto",
            name="bid",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="puntos", to="bids.bid"
            ),
        ),
    ]
