# Generated by Django 3.1.2 on 2020-10-08 13:46

from django.db import migrations, models


def migrate_puntos(apps, _):
    bid_model = apps.get_model("bids", "Bid")
    for bid in bid_model.objects.all():
        puntos = bid.puntos.all()
        for idx, punto in enumerate(puntos):
            if idx == 0:
                bid.temp_puntos.add(punto)
            else:
                new_bid = bid_model.objects.create(user=bid.user, offer=bid.offer)
                new_bid.temp_puntos.add(punto)


class Migration(migrations.Migration):
    dependencies = [
        ("bids", "0016_bid_canal_paid"),
        ("users", "0030_auto_20200930_1514"),
    ]
    operations = [
        migrations.AddField(
            model_name="punto",
            name="temp_bid",
            field=models.ManyToManyField(related_name="temp_puntos", to="bids.Bid"),
        ),
        migrations.RunPython(migrate_puntos, reverse_code=migrations.RunPython.noop),
    ]
