# Generated by Django 3.1.2 on 2020-10-08 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0031_punto_temp_bid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="punto",
            name="bid",
        ),
    ]
