# Generated by Django 3.1.2 on 2020-10-08 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0032_remove_punto_bid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="punto",
            old_name="temp_bid",
            new_name="bid",
        ),
    ]
