# Generated by Django 3.1.2 on 2020-10-08 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bids", "0016_bid_canal_paid"),
        ("users", "0033_auto_20201008_1352"),
    ]

    operations = [
        migrations.AlterField(
            model_name="punto",
            name="bid",
            field=models.ManyToManyField(related_name="puntos", to="bids.Bid"),
        ),
    ]
