# Generated by Django 3.1.2 on 2020-10-13 08:56

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0034_auto_20201008_1352"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attachment",
            name="attachment_type",
            field=models.CharField(
                choices=[
                    ("factura", "Factura"),
                    ("factura_1", "Factura reverso"),
                    ("dni1", "DNI"),
                    ("dni2", "DNI reverse side"),
                    ("cif1", "CIF"),
                    ("recibo1", "Recibo de Autónomo"),
                    ("repr_legal", "Foto DNI Representante Legal"),
                    ("name_changed", "Cambio de nombre"),
                    ("arredamiento", "Contrato arredamiento"),
                    ("factura_gas_1", "Factura GAS"),
                    ("factura_gas_2", "Factura GAS reverso"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="punto",
            name="province",
            field=apps.users.models.MyCharField(
                blank=True,
                choices=[
                    ("A CORUNA", "A CORUNA"),
                    ("ALAVA", "ALAVA"),
                    ("ALBACETE", "ALBACETE"),
                    ("ALICANTE", "ALICANTE"),
                    ("ALMERIA", "ALMERIA"),
                    ("ASTURIAS", "ASTURIAS"),
                    ("AVILA", "AVILA"),
                    ("BADAJOZ", "BADAJOZ"),
                    ("BALEARS", "BALEARS"),
                    ("BARCELONA", "BARCELONA"),
                    ("BURGOS", "BURGOS"),
                    ("CACERES", "CACERES"),
                    ("CADIZ", "CADIZ"),
                    ("CANTABRIA", "CANTABRIA"),
                    ("CASTELLON", "CASTELLON"),
                    ("CIUDAD REAL", "CIUDAD REAL"),
                    ("CORDOBA", "CORDOBA"),
                    ("CUENCA", "CUENCA"),
                    ("GIPUZKOA", "GIPUZKOA"),
                    ("GIRONA", "GIRONA"),
                    ("GRANADA", "GRANADA"),
                    ("GUADALAJARA", "GUADALAJARA"),
                    ("HUELVA", "HUELVA"),
                    ("HUESCA", "HUESCA"),
                    ("JAEN", "JAEN"),
                    ("LA RIOJA", "LA RIOJA"),
                    ("LAS PALMAS", "LAS PALMAS"),
                    ("LEON", "LEON"),
                    ("LLEIDA", "LLEIDA"),
                    ("LUGO", "LUGO"),
                    ("MADRID", "MADRID"),
                    ("MALAGA", "MALAGA"),
                    ("MURCIA", "MURCIA"),
                    ("NAVARRA", "NAVARRA"),
                    ("OURENSE", "OURENSE"),
                    ("PALENCIA", "PALENCIA"),
                    ("PONTEVEDRA", "PONTEVEDRA"),
                    ("SALAMANCA", "SALAMANCA"),
                    ("SANTA CRUZ DE TENERIFE", "SANTA CRUZ DE TENERIFE"),
                    ("SEGOVIA", "SEGOVIA"),
                    ("SEVILLA", "SEVILLA"),
                    ("SORIA", "SORIA"),
                    ("TARRAGONA", "TARRAGONA"),
                    ("TERUEL", "TERUEL"),
                    ("TOLEDO", "TOLEDO"),
                    ("VALENCIA", "VALENCIA"),
                    ("VALLADOLID", "VALLADOLID"),
                    ("VIZCAYA", "VIZCAYA"),
                    ("ZAMORA", "ZAMORA"),
                    ("ZARAGOZA", "ZARAGOZA"),
                ],
                max_length=255,
                null=True,
                verbose_name="Province",
            ),
        ),
    ]
