# Generated by Django 3.1.2 on 2020-11-03 16:52

import django.core.validators
from django.db import migrations, models


def migrate_phones(apps, _):
    phones_model = apps.get_model('users', 'Phone')
    for phone in phones_model.objects.all():
        user = phone.user
        if phone.phone_type == 'mobile' and not user.phone:
            user.phone = phone.number
            user.save(update_fields=['phone'])
        elif phone.phone_type == 'city' and not user.phone_city:
            user.phone = phone.number
            user.save(update_fields=['phone'])


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_customuser_observations'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_city',
            field=models.CharField(blank=True, max_length=9, null=True, validators=[django.core.validators.RegexValidator(message='Utilice este formato para su número de teléfono: 999999999', regex='^[1-9]\\d{8}$')], verbose_name='City phone number'),
        ),
        migrations.RunPython(migrate_phones, reverse_code=migrations.RunPython.noop),
    ]
