# Generated by Django 3.1.2 on 2020-11-03 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_customuser_phone_city'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Phone',
        ),
    ]
