# Generated by Django 3.1.5 on 2021-01-11 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0041_delete_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="cif_dni",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name="CIF/DNI"),
        ),
    ]
