# Generated by Django 3.1.5 on 2021-01-29 11:16

import django.contrib.postgres.fields.citext
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0045_auto_20210125_2136"),
    ]

    operations = [
        migrations.AlterField(
            model_name="punto",
            name="cups_gas",
            field=django.contrib.postgres.fields.citext.CICharField(
                blank=True, max_length=25, null=True, verbose_name="CUPS GAS"
            ),
        ),
        migrations.AlterField(
            model_name="punto",
            name="cups_luz",
            field=django.contrib.postgres.fields.citext.CICharField(
                blank=True, max_length=25, null=True, verbose_name="CUPS"
            ),
        ),
    ]
