# Generated by Django 3.1.5 on 2021-02-01 17:15

import django.contrib.postgres.fields.citext
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0046_auto_20210129_1116"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="company_name",
            field=django.contrib.postgres.fields.citext.CICharField(
                blank=True, max_length=255, null=True, verbose_name="Company name"
            ),
        ),
    ]
