# Generated by Django 3.1.5 on 2021-02-08 18:52

import apps.users.validators
import django.contrib.postgres.fields.citext
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0048_remove_punto_bid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="punto",
            name="cups_gas",
            field=django.contrib.postgres.fields.citext.CICharField(
                blank=True,
                max_length=25,
                null=True,
                validators=[apps.users.validators.cups_validator],
                verbose_name="CUPS GAS",
            ),
        ),
        migrations.AlterField(
            model_name="punto",
            name="cups_luz",
            field=django.contrib.postgres.fields.citext.CICharField(
                blank=True,
                max_length=25,
                null=True,
                validators=[apps.users.validators.cups_validator],
                verbose_name="CUPS",
            ),
        ),
    ]
