# Generated by Django 3.1.5 on 2021-02-11 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0049_auto_20210208_1852"),
    ]

    operations = [
        migrations.RemoveField(model_name="customuser", name="fecha_firma",),
    ]
