# Generated by Django 3.1.5 on 2021-06-28 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0051_auto_20210304_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='attachment_type',
            field=models.CharField(choices=[('factura', 'Factura'), ('factura_1', 'Factura reverso'), ('dni1', 'DNI'), ('dni2', 'DNI reverse side'), ('cif1', 'CIF'), ('recibo1', 'Recibo de Autónomo'), ('repr_legal', 'Foto DNI Representante Legal'), ('name_changed', 'Cambio de nombre'), ('arredamiento', 'Contrato arredamiento'), ('factura_gas_1', 'Factura GAS'), ('factura_gas_2', 'Factura GAS reverso'), ('contrato', 'Contrato'), ('anexo', 'Anexo'), ('hoja', 'HOJA DE ACTIVACIÓN FUTURA')], max_length=20),
        ),
    ]
