# Generated by Django 3.1.5 on 2021-06-30 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0052_auto_20210628_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='punto',
            name='c4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='punto',
            name='c5',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='punto',
            name='c6',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='punto',
            name='p4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='punto',
            name='p5',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='punto',
            name='p6',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
