# Generated by Django 3.1.5 on 2021-07-07 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0053_auto_20210630_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='renovated',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
