# Generated by Django 3.1.5 on 2021-07-28 15:02

import apps.users.models
import django.contrib.postgres.fields
from django.db import migrations, models


def set_default_permissions(apps, _):
    users = apps.get_model("users", "CustomUser")
    for user in users.objects.filter(role="agent"):
        permissions = user.permissions
        permissions.append("facturacion")
        user.permissions = permissions
        user.save(update_fields=["permissions"])


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0054_customuser_renovated"),
    ]

    operations = [
        migrations.RunPython(set_default_permissions, reversed=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="customuser",
            name="permissions",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("offers", "Offers"),
                        ("calculator", "Calculator"),
                        ("leeds_access", "Leeds"),
                        ("facturacion", "Facturacion"),
                    ],
                    max_length=30,
                ),
                default=apps.users.models.get_default_user_permissions,
                help_text="Possible values: ",
                size=None,
            ),
        ),
    ]
