# Generated by Django 3.1.5 on 2021-08-09 11:19

from django.db import migrations, models


def migrate_category(apps, _):
    def convert_category(category) -> int:
        if category == "physical":
            return 0
        elif category == "business":
            return 1
        elif category == "autonomous":
            return 2
        return 0

    punto_model = apps.get_model("users", "Punto")
    for punto in punto_model.objects.all():
        punto.client_type = convert_category(punto.category)
        punto.save(update_fields=["client_type"])


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0055_auto_20210728_1502"),
    ]

    operations = [
        migrations.AddField(
            model_name="punto",
            name="client_type",
            field=models.IntegerField(choices=[(0, "Individual"), (1, "Business"), (2, "Autónomo")], default=0),
        ),
        migrations.RunPython(migrate_category, reverse_code=migrations.RunPython.noop),
    ]
