# Generated by Django 3.1.5 on 2021-08-09 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0056_punto_client_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='punto',
            name='category',
        ),
    ]
