# Generated by Django 3.1.5 on 2021-08-20 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0058_punto_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='punto',
            name='is_name_changed',
            field=models.BooleanField(blank=True, null=True, verbose_name='Is name changed'),
        ),
    ]
