# Generated by Django 3.1.5 on 2021-09-30 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0062_callvisittoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.IntegerField(choices=[(0, 'Firmado'), (1, 'Renovacion'), (2, 'Fidelization'), (3, 'No cliente')], default=0),
        ),
    ]
