# Generated by Django 3.1.5 on 2021-09-30 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0063_customuser_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Firmado'), (1, 'Renovacion'), (2, 'Fidelization'), (3, 'No cliente')], null=True),
        ),
    ]
