# Generated by Django 3.1.5 on 2021-09-30 13:40

import apps.users.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0064_auto_20210930_1228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='renovated',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='permissions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('offers', 'Offers'), ('calculator', 'Calculator'), ('leeds_access', 'Leeds')], max_length=30), default=apps.users.models.get_default_user_permissions, help_text='Possible values: ', size=None),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Firmado'), (1, 'Renovacion'), (2, 'Fidelization'), (3, 'No cliente'), (4, 'Tramitacion')], null=True),
        ),
    ]
