# Generated by Django 3.1.5 on 2021-12-10 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0065_auto_20210930_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Firmado'), (1, 'Renovacion'), (2, 'Fidelizacion'), (3, 'No cliente'), (4, 'Tramitacion')], null=True),
        ),
    ]
