# Generated by Django 3.0.7 on 2020-08-08 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bid",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(default="Pendiente tramitacion", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="BidStory",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "old_status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("purchase", "Purchase"),
                            ("purchase_updated", "Purchase updated"),
                            ("success", "Success"),
                            ("error", "Error"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("purchase", "Purchase"),
                            ("purchase_updated", "Purchase updated"),
                            ("success", "Success"),
                            ("error", "Error"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.TextField(blank=True, null=True)),
                ("dt", models.DateTimeField(auto_now_add=True)),
                ("bid", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="bids.Bid")),
            ],
        ),
    ]
