# Generated by Django 3.0.7 on 2020-06-11 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0004_auto_20200610_1415"),
        ("bids", "0003_auto_20200611_1423"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bid",
            name="offer",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="calculator.Offer"),
        ),
    ]
