# Generated by Django 3.0.7 on 2020-06-11 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bids", "0004_auto_20200611_1426"),
    ]

    operations = [
        migrations.RemoveField(model_name="bid", name="annual_consumption",),
    ]
