# Generated by Django 3.0.7 on 2020-06-11 15:23

import apps.bids.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bids", "0005_remove_bid_annual_consumption"),
    ]

    operations = [
        migrations.AddField(
            model_name="bid",
            name="status",
            field=models.CharField(
                choices=apps.bids.models.Bid.BID_STATUS_CHOICES,
                default="initial",
                max_length=50,
            ),
        ),
    ]
