# Generated by Django 3.0.7 on 2020-08-09 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0007_auto_20200809_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidstory',
            name='bid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='bids.Bid'),
        ),
    ]
