# Generated by Django 3.0.7 on 2020-06-15 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0007_bid_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='card',
        ),
    ]
