# Generated by Django 3.1 on 2020-08-16 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0008_auto_20200809_0202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bid',
            options={'verbose_name': 'Bid', 'verbose_name_plural': 'Bids'},
        ),
    ]
