# Generated by Django 3.0.7 on 2020-06-15 03:56

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0008_remove_bid_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='status',
            field=django_fsm.FSMField(default='new', max_length=50, protected=True),
        ),
    ]
