# Generated by Django 3.1 on 2020-09-11 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0009_auto_20200816_0346'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='final_agent_commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='bid',
            name='final_canal_commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
