# Generated by Django 3.1 on 2020-09-11 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0010_auto_20200911_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
