# Generated by Django 3.1 on 2020-09-11 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0011_bid_paid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='final_agent_commission',
            new_name='commission',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='final_canal_commission',
        ),
    ]
