# Generated by Django 3.1 on 2020-09-22 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0013_auto_20200917_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidstory',
            name='internal_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
