# Generated by Django 3.1 on 2020-09-24 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0014_bidstory_internal_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='canal_commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
