# Generated by Django 3.0.7 on 2020-07-10 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0015_auto_20200701_0041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='c1',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='c2',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='c3',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='p1',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='p2',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='p3',
        ),
    ]
