# Generated by Django 3.1 on 2020-09-24 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0015_bid_canal_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='canal_paid',
            field=models.BooleanField(default=False),
        ),
    ]
