# Generated by Django 3.1.5 on 2021-02-07 03:18

from django.db import migrations, models

from apps.users.utils import PENDIENTE_PAGO


def migrate_ff(apps, _):
    Bid = apps.get_model("bids", "Bid")
    for bid in Bid.objects.all():
        stories = bid.stories.all()
        for story in stories:
            ss = story.status.lower()
            if PENDIENTE_PAGO.lower() in ss or ss == "ok" or ss == "pagado":
                bid.fecha_firma = ss.dt
                bid.save()
        if not bid.fecha_firma:
            bid.fecha_firma = bid.created_at
            bid.save()


class Migration(migrations.Migration):

    dependencies = [
        ("bids", "0017_bid_offer_status"),
    ]

    operations = [
        migrations.AddField(model_name="bid", name="fecha_firma", field=models.DateTimeField(blank=True, null=True),),
        migrations.RunPython(migrate_ff, reverse_code=migrations.RunPython.noop),
    ]
