# Generated by Django 3.1.5 on 2021-02-07 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0047_auto_20210201_1715"),
        ("bids", "0018_bid_fecha_firma"),
    ]

    operations = [
        migrations.AddField(
            model_name="bid",
            name="punto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="temp",
                to="users.punto",
            ),
        ),
    ]
