# Generated by Django 3.1.5 on 2021-02-08 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0048_remove_punto_bid"),
        ("bids", "0019_bid_punto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bid",
            name="punto",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="users.punto"
            ),
        ),
    ]
