# Generated by Django 3.1.5 on 2021-02-07 03:46

from django.db import migrations, models
import django.db.models.deletion


def delete_empty_bids(apps, _):
    Bid = apps.get_model("bids", "Bid")
    Bid.objects.filter(punto__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0048_remove_punto_bid"),
        ("bids", "0019_bid_punto"),
    ]

    operations = [
        migrations.RunPython(delete_empty_bids, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="bid",
            name="punto",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="users.punto"),
        ),
    ]
