# Generated by Django 3.1.5 on 2021-02-08 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0049_auto_20210208_1852"),
        ("bids", "0020_auto_20210208_1809"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bid",
            name="punto",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="users.punto"),
        ),
    ]
