# Generated by Django 3.1.5 on 2021-02-12 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bids", "0021_auto_20210208_1852"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bidstory",
            name="status",
            field=models.CharField(default="Pendiente tramitación", max_length=50),
        ),
    ]
