# Generated by Django 3.1.5 on 2021-02-16 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bids", "0022_auto_20210212_1627"),
    ]

    operations = [
        migrations.AddField(
            model_name="bid",
            name="fecha_de_cobro_prevista",
            field=models.DateField(blank=True, null=True, verbose_name="Fecha de cobro prevista"),
        ),
    ]
