# Generated by Django 3.1.5 on 2021-02-22 00:22

from django.db import migrations, models


def pre_migrate(apps, _):
    bm = apps.get_model("bids", "Bid")
    bm.objects.filter(offer_status="").update(offer_status=None)


def migrate_this(apps, _):
    bm = apps.get_model("bids", "Bid")
    for bid in bm.objects.select_related("offer__company"):
        if bid.offer.company.offer_status_used is False or not bid.offer_status:
            bid.offer_status = None
        elif str(bid.offer_status) == "0":
            bid.offer_status = True
        elif str(bid.offer_status) == "1":
            bid.offer_status = False
        else:
            continue
        bid.save(update_fields=["offer_status"])


class Migration(migrations.Migration):

    dependencies = [
        ("bids", "0023_bid_fecha_de_cobro_prevista"),
    ]

    operations = [
        migrations.RunPython(pre_migrate, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="bid",
            name="offer_status",
            field=models.BooleanField(blank=True, choices=[(True, "FIRMADA"), (False, "PTE FIRMAR")], null=True),
        ),
        migrations.RunPython(migrate_this, reverse_code=migrations.RunPython.noop),
    ]
