# Generated by Django 3.0.7 on 2020-06-15 03:28

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bids", "0008_remove_bid_card"),
        ("cards", "0002_auto_20200611_1538"),
    ]

    operations = [
        migrations.RemoveField(model_name="card", name="address",),
        migrations.RemoveField(model_name="card", name="cups",),
        migrations.RemoveField(model_name="card", name="name",),
        migrations.AddField(
            model_name="card",
            name="bid",
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to="bids.Bid"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="card",
            name="data",
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
            preserve_default=False,
        ),
    ]
