# Generated by Django 3.0.7 on 2020-06-15 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bids", "0008_remove_bid_card"),
        ("cards", "0003_auto_20200615_0328"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="source",
            field=models.CharField(choices=[("default", "Default")], default="default", max_length=30),
        ),
        migrations.DeleteModel(name="Source",),
    ]
