# Generated by Django 3.0.7 on 2020-06-15 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0005_remove_card_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="CardAttachment",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "attchament_type",
                    models.CharField(
                        choices=[
                            ("factura", "Factura"),
                            ("dni1", "DNI"),
                            ("dni2", "DNI reverse side"),
                            ("cif1", "CIF"),
                            ("cif2", "CIF reverse side"),
                        ],
                        max_length=10,
                    ),
                ),
                ("card", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="cards.Card")),
            ],
        ),
    ]
