# Generated by Django 3.0.7 on 2020-06-15 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0006_cardattachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="cardattachment",
            name="attchament",
            field=models.FileField(default=None, upload_to=""),
            preserve_default=False,
        ),
    ]
