# Generated by Django 3.0.7 on 2020-06-29 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0008_auto_20200615_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardattachment',
            name='attachment_type',
            field=models.CharField(choices=[('factura', 'Factura'), ('factura_1', 'Factura reverso'), ('dni1', 'DNI'), ('dni2', 'DNI reverse side'), ('cif1', 'CIF'), ('cif2', 'CIF reverse side')], max_length=10),
        ),
    ]
