# Generated by Django 3.0.7 on 2020-07-06 11:53

import apps.cards.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0008_auto_20200629_2055'),
        ('cards', '0009_auto_20200629_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Punto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', apps.cards.models.MyCharField(max_length=100, null=True)),
                ('poblacion', apps.cards.models.MyCharField(max_length=100, null=True)),
                ('direccion', apps.cards.models.MyCharField(max_length=100, null=True)),
                ('postalcode', apps.cards.models.MyCharField(max_length=100, null=True)),
                ('last_time_company_luz_changed', models.DateField()),
                ('last_time_company_gas_changed', models.DateField()),
                ('cups_luz', apps.cards.models.MyCharField(max_length=100, null=True)),
                ('cups_gas', apps.cards.models.MyCharField(max_length=100, null=True)),
                ('tarif_luz', apps.cards.models.MyCharField(max_length=100, null=True)),
                ('tarif_gas', apps.cards.models.MyCharField(max_length=100, null=True)),
                ('p1', models.FloatField()),
                ('p2', models.FloatField()),
                ('p3', models.FloatField()),
                ('c1', models.FloatField()),
                ('c2', models.FloatField()),
                ('c3', models.FloatField()),
                ('consumo_annual_luz', models.FloatField()),
                ('consumo_annual_gas', models.FloatField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.Card')),
                ('company_gas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_gas', to='calculator.Company')),
                ('company_luz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_luz', to='calculator.Company')),
            ],
        ),
    ]
