# Generated by Django 3.0.7 on 2020-07-06 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0008_auto_20200629_2055'),
        ('cards', '0010_punto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='punto',
            name='c1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='punto',
            name='c2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='punto',
            name='c3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='punto',
            name='company_gas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_gas', to='calculator.Company'),
        ),
        migrations.AlterField(
            model_name='punto',
            name='company_luz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_luz', to='calculator.Company'),
        ),
        migrations.AlterField(
            model_name='punto',
            name='consumo_annual_gas',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='punto',
            name='consumo_annual_luz',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='punto',
            name='last_time_company_gas_changed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='punto',
            name='last_time_company_luz_changed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='punto',
            name='p1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='punto',
            name='p2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='punto',
            name='p3',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
