# Generated by Django 3.1.5 on 2021-09-30 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20200816_0346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unreadmessage',
            name='message',
        ),
        migrations.RemoveField(
            model_name='unreadmessage',
            name='user',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='UnreadMessage',
        ),
    ]
